### PR TITLE
Fixes #23 

### LINKED ISSUE #23: Unable to open "JVM Settings" in Preferences in Eclipse 2020-09
Unable to open "JVM Settings" in Preferences in Eclipse 2020-09 (4.17.0).
The following error message is displayed:

> Could Not Accept Changes
> The currently displayed page contains invalid values.

### PR DESCRIPTION
**Pull request by boulik**
Fixes #23

### CODE REVIEW

**Comment by markuskeunecke** [comment]
@boulik : Why did you choose to add a .project file to repository root? Otherwise the PR looks fine to me.

**Comment by boulik** [comment]
Eclipse has generate this file and I thought it shouldn't be a problem. :( 
Should I just commit deleting that file, or should I prepare a new PR?

**Comment by markuskeunecke** [comment]
As it does no real harm and I see some advantages I simply merge this PR. Thank you for your contribution @boulik

**Comment by jochenw** [comment]
Besides, for a project providing an Eclipse plugin, it seems to be perfectely fine to have a .project.

**Pull request merged**
